version: '3.8'

#adiciona volume para persistir dados do prometheus e do grafana
volumes:
  data: {}
  grafana: {}
  
# services:

  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #     - data:/prometheus
  #   networks:
  #     - candystore-bridge
  #   restart: always

  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - grafana:/var/lib/grafana
  #   networks:
  #     - candystore-bridge
  #   restart: always

  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
  #   networks:
  #     - candystore-bridge
  #   restart: always


networks:
  zpe-bridge:
    driver: bridge
