@startuml
!theme blueprint

|Start|
:Receive request to get user details;
:Validate request parameters;
if (Request contains valid parameters?) then (yes)
    :Query Role-API for role information;
    if (Role information retrieved successfully?) then (yes)
        :Query user information based on provided parameters;
        if (User information retrieved successfully?) then (yes)
            #green:Finish;
            stop
        else (no)
            :Return error message to user;
            #4d3900:Error: User information retrieval failed;
            stop
        endif
    else (no)
        :Return error message to user;
        #4d3900:Error: Role information retrieval failed;
        stop
    endif
else (no)
    :Query Role-API for role information;
    :Query all users from the database;
    if (Users retrieved successfully?) then (yes)
        #green:Finish;
        stop
    else (no)
        :Return error message to user;
        #4d3900:Error: User information retrieval failed;
        stop
    endif
endif

@enduml
